###
DELETE http://localhost:8080/book/delete-author/1

###
PUT http://localhost:8080/book/unlink
Content-Type: application/json

{"idAuthor": 1, "idBook": 2}

###
POST http://localhost:8080/book/loan
Content-Type: application/json

{"idCopy": 2, "idPerson": 1, "finalDate": "11-12-2022"}

###
GET http://localhost:8080/book/not-borrowed/3

###
PATCH http://localhost:8080/book/edit-loan
Content-Type: application/json

{"id": 11091, "finalDate": "13-10-2022", "initDate":"14-10-2022", "book_id":2, "person_id":1}