###
DELETE http://localhost:8080/book/delete-author/1

###
PUT http://localhost:8080/book/unlink
Content-Type: application/json

{"idAuthor": 1, "idBook": 2}

###
POST http://localhost:8080/book/loan
Content-Type: application/json

{"idCopy": 2, "idPerson": 1, "finalDate": "11-12-2022"}

###
GET http://localhost:8080/book/not-borrowed/3